In [21]:
import pandas as pd
import numpy as np
from datetime import datetime
import os

In [38]:

def create_df(fpath):
    # Read csv File and store into Pandas data frame
    fpath = os.path.join("data/taxi_data_12-31-2016.csv")
    newdf = pd.read_csv(fpath)
    return newdf
#end create_df(fpath)

In [39]:
cdf = create_df("GDP/GDP_Data.csv")
cdf.head()

,trip_id,trip_start_timestamp,trip_end_timestamp,fare,pickup_latitude,pickup_longitude,dropoff_latitude,dropoff_longitude
0,32761dfbd17e17c7594369a27b47d01e42b9d81c,12/31/2016 19:30,12/31/2016 19:30,0.0,NaN,NaN,NaN,NaN
1,79429ce2f9829733a2b1b6f69ae5b142328657a7,12/31/2016 9:15,12/31/2016 9:15,5.0,NaN,NaN,NaN,NaN
2,7e0faa899f6a26956b36869b9b1611eada9fcc89,12/31/2016 14:45,12/31/2016 14:45,5.0,NaN,NaN,NaN,NaN
3,81db25b59367547741729e1146d9b4231e992dc6,12/31/2016 23:00,12/31/2016 23:15,8.5,NaN,NaN,NaN,NaN
4,9265d84f94934a4b36b3bc2d96f93e48e789745a,12/31/2016 5:00,1/1/2017 0:00,0.0,NaN,NaN,NaN,NaN

In [40]:
#newdf = cdf.drop(columns=['Trip ID', 'Taxi ID', 'Tolls', 'Tips', 'Pickup Census Tract', 'Dropoff Census Tract', 'Pickup Community Area', 'Dropoff Community Area', 'Extras', 'Trip Total', 'Payment Type', 'Company', 'Pickup Centroid Location', 'Dropoff Centroid  Location'])

In [41]:
newdf.dtypes

Trip Start Timestamp     object
Trip End Timestamp       object
Trip Seconds              int64
Trip Miles              float64
Fare                    float64
Pickup Latitude         float64
Pickup Longitude        float64
Dropoff Latitude        float64
Dropoff Longitude       float64
dtype: object

In [42]:
newdf.head()

,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Fare,Pickup Latitude,Pickup Longitude,Dropoff Latitude,Dropoff Longitude
0,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,660,4.55,14.50,41.899602,-87.633308,41.922686,-87.649489
1,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,420,1.60,7.50,41.922686,-87.649489,41.901207,-87.676356
2,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,0,0.00,3.25,41.901207,-87.676356,41.986712,-87.663416
3,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,480,2.50,9.25,41.975171,-87.687516,41.986712,-87.663416
15,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,480,0.10,8.75,41.965812,-87.655879,41.975171,-87.687516

In [43]:
# drop columns with NAs
#cleandf = cdf.dropna(axis=1, how ='all')
# drop rows with 4 or more NAs

newdf = newdf.dropna()
newdf.shape

(816, 9)

In [44]:
newdf.head(100)

,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Fare,Pickup Latitude,Pickup Longitude,Dropoff Latitude,Dropoff Longitude
0,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,660,4.55,14.50,41.899602,-87.633308,41.922686,-87.649489
1,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,420,1.60,7.50,41.922686,-87.649489,41.901207,-87.676356
2,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,0,0.00,3.25,41.901207,-87.676356,41.986712,-87.663416
3,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,480,2.50,9.25,41.975171,-87.687516,41.986712,-87.663416
15,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,480,0.10,8.75,41.965812,-87.655879,41.975171,-87.687516
16,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,180,0.00,5.50,41.901207,-87.676356,41.901207,-87.676356
63,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,540,1.34,7.50,41.907492,-87.635760,41.892042,-87.631864
64,01/01/2017 12:00:00 AM,01/01/2017 12:30:00 AM,1260,0.70,10.00,41.880994,-87.632746,41.892508,-87.626215
65,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,120,0.30,4.25,41.899156,-87.626211,41.899156,-87.626211
66,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,240,0.30,4.50,41.892042,-87.631864,41.892042,-87.631864
67,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,720,0.00,10.50,41.965812,-87.655879,41.947792,-87.683835
68,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,660,0.00,10.00,41.965812,-87.655879,41.968069,-87.721559
69,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,540,0.00,7.25,41.899156,-87.626211,41.905858,-87.630865
70,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,420,1.40,7.00,41.944227,-87.655998,41.944227,-87.655998
71,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,540,1.30,7.50,41.880994,-87.632746,41.905858,-87.630865
72,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,360,0.62,5.50,41.907492,-87.635760,41.900221,-87.629105
73,01/01/2017 12:00:00 AM,01/01/2017 12:30:00 AM,1200,5.90,18.50,41.899602,-87.633308,41.944227,-87.655998
74,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,360,1.50,6.75,41.892042,-87.631864,41.907492,-87.635760
75,01/01/2017 12:00:00 AM,01/01/2017 12:30:00 AM,1260,0.30,10.00,41.880994,-87.632746,41.884987,-87.620993
76,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,180,0.70,5.00,41.944227,-87.655998,41.944227,-87.655998
77,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,360,0.60,5.50,41.944227,-87.655998,41.944227,-87.655998
78,01/01/2017 12:00:00 AM,01/01/2017 12:15:00 AM,1140,2.30,11.50,41.880994,-87.632746,41.899156,-87.626211
79,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,660,0.00,7.25,41.900221,-87.629105,41.892042,-87.631864
80,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,240,0.60,4.75,41.952823,-87.653244,41.942692,-87.651771
81,01/01/2017 12:00:00 AM,01/01/2017 12:15:00 AM,1200,0.30,17.00,41.899602,-87.633308,41.944227,-87.655998
82,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,660,1.70,8.50,41.879255,-87.642649,41.884987,-87.620993
83,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,240,0.60,5.00,41.892073,-87.628874,41.880994,-87.632746
84,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,321,1.03,6.00,41.892042,-87.631864,41.898332,-87.620763
85,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,120,0.40,4.25,41.880994,-87.632746,41.880994,-87.632746
86,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,480,1.00,6.50,41.892042,-87.631864,41.884987,-87.620993
...,...,...,...,...,...,...,...,...,...
128,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,360,1.30,6.75,41.892508,-87.626215,41.885300,-87.642808
129,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,300,1.70,5.75,41.901207,-87.676356,41.901207,-87.676356
130,01/01/2017 12:00:00 AM,01/01/2017 12:15:00 AM,660,0.10,9.25,41.899602,-87.633308,41.922686,-87.649489
131,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,540,3.20,11.00,41.922686,-87.649489,41.944227,-87.655998
132,01/01/2017 12:00:00 AM,01/01/2017 12:15:00 AM,840,0.00,19.75,41.899602,-87.633308,41.808916,-87.596183
133,01/01/2017 12:00:00 AM,01/01/2017 12:30:00 AM,1200,7.10,21.25,41.899602,-87.633308,41.900070,-87.720918
134,01/01/2017 12:00:00 AM,01/01/2017 12:15:00 AM,120,0.50,4.50,41.953582,-87.723452,41.953582,-87.723452
135,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,60,0.00,3.25,41.892508,-87.626215,41.892508,-87.626215
136,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,600,3.50,12.00,41.879255,-87.642649,41.899507,-87.679600
138,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,448,1.62,7.50,41.899602,-87.633308,41.878866,-87.625192
139,01/01/2017 12:00:00 AM,01/01/2017 12:15:00 AM,360,0.00,6.50,41.899156,-87.626211,41.905858,-87.630865
140,12/31/2016 12:00:00 AM,12/31/2016 12:30:00 AM,1140,0.40,21.00,41.879255,-87.642649,41.942585,-87.656644
141,01/01/2017 12:00:00 AM,01/01/2017 12:30:00 AM,960,1.40,9.50,41.880994,-87.632746,41.884987,-87.620993
142,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,240,1.10,6.00,41.965812,-87.655879,41.965812,-87.655879
143,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,900,0.30,16.75,41.921778,-87.651062,41.880994,-87.632746
144,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,360,0.00,7.25,41.922761,-87.699155,41.901207,-87.676356
145,01/01/2017 12:00:00 AM,01/01/2017 12:15:00 AM,600,0.70,7.00,41.884987,-87.620993,41.892073,-87.628874
146,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,900,4.90,15.25,41.944227,-87.655998,41.975171,-87.687516
147,01/01/2017 12:00:00 AM,01/01/2017 12:30:00 AM,1560,1.90,12.75,41.892073,-87.628874,41.880994,-87.632746
148,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,240,1.30,6.25,41.880994,-87.632746,41.885281,-87.657233
149,01/01/2017 12:00:00 AM,01/01/2017 12:15:00 AM,960,0.10,11.50,41.899737,-87.664954,41.907520,-87.626659
150,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,180,0.50,4.50,41.947792,-87.683835,41.944227,-87.655998
151,01/01/2017 12:00:00 AM,01/01/2017 12:00:00 AM,300,0.90,5.75,41.922686,-87.649489,41.922686,-87.649489
152,12/31/2016 12:00:00 AM,12/31/2016 12:15:00 AM,540,1.50,7.50,41.892508,-87.626215,41.892658,-87.652534
153,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,480,7.40,7.00,41.907492,-87.635760,41.892073,-87.628874
154,12/31/2016 12:00:00 AM,12/31/2016 12:00:00 AM,300,0.70,5.50,41.899602,-87.633308,41.878866,-87.625192
155,01/01/2017 12:00:00 AM,01/01/2017 12:15:00 AM,867,4.11,14.25,41.899602,-87.633308,41.944227,-87.655998
156,01/01/2017 12:00:00 AM,01/01/2017 12:15:00 AM,1140,3.10,12.50,41.922686,-87.649489,41.899602,-87.633308
157,01/01/2017 12:00:00 AM,01/01/2017 12:15:00 AM,420,0.70,6.00,41.892042,-87.631864,41.895033,-87.619711
158,01/01/2017 12:00:00 AM,01/01/2017 12:30:00 AM,1200,0.20,13.75,41.900266,-87.632109,41.942585,-87.656644

In [49]:
#newdf = newdf.rename({'Pickup Centroid Latitude':'Pickup Latitude',
#              'Pickup Centroid Longitude':'Pickup Longitude', 
#             'Dropoff Centroid Latitude':'Dropoff Latitude', 
#              'Dropoff Centroid Longitude':'Dropoff Longitude'}, axis=1)

In [51]:
# Push the remade DataFrame to a new CSV file
newdf.to_csv("CleanData/data_clean.csv", index=False, header=True)